name: Auto Assign
run-name: ${{ github.actor }} - Auto Assign
on:
  workflow_dispatch:
  issues:
    types: [opened]
jobs:
  run:
    uses: jtorleon-studios-team/.workflows/.github/workflows/auto-assign.yml@main
    secrets: inherit
