name: Notify Discord
run-name: ${{ github.actor }} - Notify Discord
on:
  #push:
  workflow_dispatch:
jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Get version from last release.json
        id: get_last_version
        run: |
          LAST_VERSION=$(curl -s https://api.github.com/repos/jtorleon-studios-team/maintenance-warden-light/releases/latest | jq -r '.tag_name')
          echo "LAST_VERSION=$LAST_VERSION" >> $GITHUB_ENV

      - name: Get version from package.json
        id: get_version
        run: |
          VERSION=$(node -p "require('./package.json').version")
          echo "VERSION=$VERSION" >> $GITHUB_ENV

      - name: "send message"
        run: |
          echo "LAST_VERSION $LAST_VERSION"
          echo "VERSION $VERSION"

          if [ "$LAST_VERSION" != "v$VERSION" ]; then
            REPO_NAME=$(echo $GITHUB_REPOSITORY | cut -d'/' -f2)
            PUBLIC_REPO_NAME=$(echo $REPO_NAME | sed 's/\.private$//')
            icon_pack_url="https://raw.githubusercontent.com/jtorleon-studios-team/$PUBLIC_REPO_NAME/refs/heads/main/icon.png"
            messageToJson=$( jq -n\
              --arg title "$MOD_NAME has been updated" \
              --arg version "$VERSION" \
              --arg thumbnail_url "$icon_pack_url" \
              '{
                content: null,
                embeds: [
                  {
                    title: $title,
                    color: null,
                    fields: [
                      {name: "🚀   Version", value: $version},
                      {name: "🚀   Documentation", value: "https://maintenance-warden-light.pages.dev/"},
                      {name: "🚀   Repository", value: "https://github.com/jtorleon-studios-team/maintenance-warden-light"}
                    ],
                    thumbnail: {url: $thumbnail_url}
                  }
                ]
              }'\
            )

            curl \
              -H "Content-Type: application/json" \
              -d "${messageToJson}" \
              ${{ secrets.DISCORD }}
            echo "success message"

            FILE_PATH="./changelog.md"
            curl -X POST ${{ secrets.DISCORD }} \
              -H "Content-Type: multipart/form-data" \
              -F "file=@$FILE_PATH"
            
            echo "success message and file sent"
          fi
