name: Notify Discord
run-name: ${{ github.actor }} - Notify Discord
on:
  push:
    tags:
      - "*.*.*"
  workflow_dispatch:
permissions:
  contents: read
jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Get version from package.json
        id: get_version
        run: |
          VERSION=$(node -p "require('./package.json').version")
          echo "VERSION=$VERSION" >> $GITHUB_ENV

      - name: "send message to discord"
        run: |
          echo "VERSION $VERSION"
          REPO_NAME=$(echo $GITHUB_REPOSITORY | cut -d'/' -f2)
          messageToJson=$( jq -n\
            --arg title "$REPO_NAME has been updated" \
            --arg version "$VERSION" \
            '{
              content: null,
              embeds: [
                {
                  title: $title,
                  color: null,
                  fields: [
                    {name: "🚀   Version", value: $version},
                    {name: "🚀   Documentation", value: "https://maintenance-warden-light.pages.dev/"},
                    {name: "🚀   Repository", value: "https://github.com/jtorleon-studios-team/maintenance-warden-light"}
                  ],
                  thumbnail: {url: "https://raw.githubusercontent.com/jtorleon-studios-team/maintenance-warden-light/refs/heads/main/.github/assets/icon.png" }
                }
              ]
            }'\
          )

          curl \
            -H "Content-Type: application/json" \
            -d "${messageToJson}" \
            ${{ secrets.DISCORD }}
          echo "success message"

          FILE_PATH="./changelog.md"
          curl -X POST ${{ secrets.DISCORD }} \
            -H "Content-Type: multipart/form-data" \
            -F "file=@$FILE_PATH"

          echo "success message and file sent"
